import React from "react";
import Navbar from "../../components/Navbar";
import { Outlet } from "react-router";

const AdminLayout = () => {
  return (
    <div>
      <Navbar />
      <main className="pt-16">
        {" "}
        {/* Add padding to prevent overlap with navbar - Generated by Copilot */}
        <Outlet /> {/* Render child routes here */}
      </main>
    </div>
  );
};

export default AdminLayout;
